# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Apple Music Song Adder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apple Music Song Adder

  pod 'Alamofire', '~> 4.0'

end
